### ***A brief revisit to Numpy***

In [1]:
import numpy as np
import math

In [2]:
np.array([i for i in range(0, 1000) if i % 11 == 0])

array([  0,  11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132,
       143, 154, 165, 176, 187, 198, 209, 220, 231, 242, 253, 264, 275,
       286, 297, 308, 319, 330, 341, 352, 363, 374, 385, 396, 407, 418,
       429, 440, 451, 462, 473, 484, 495, 506, 517, 528, 539, 550, 561,
       572, 583, 594, 605, 616, 627, 638, 649, 660, 671, 682, 693, 704,
       715, 726, 737, 748, 759, 770, 781, 792, 803, 814, 825, 836, 847,
       858, 869, 880, 891, 902, 913, 924, 935, 946, 957, 968, 979, 990])

In [3]:
np.array([i for i in range(0, 1000) if i % 11 == 0], dtype = np.float64)

array([  0.,  11.,  22.,  33.,  44.,  55.,  66.,  77.,  88.,  99., 110.,
       121., 132., 143., 154., 165., 176., 187., 198., 209., 220., 231.,
       242., 253., 264., 275., 286., 297., 308., 319., 330., 341., 352.,
       363., 374., 385., 396., 407., 418., 429., 440., 451., 462., 473.,
       484., 495., 506., 517., 528., 539., 550., 561., 572., 583., 594.,
       605., 616., 627., 638., 649., 660., 671., 682., 693., 704., 715.,
       726., 737., 748., 759., 770., 781., 792., 803., 814., 825., 836.,
       847., 858., 869., 880., 891., 902., 913., 924., 935., 946., 957.,
       968., 979., 990.])

In [4]:
fives_n_threes = np.array([i for i in range(1000) if i % 5 == 0 and i % 3 == 0])

In [5]:
fives_n_threes

array([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135, 150, 165, 180,
       195, 210, 225, 240, 255, 270, 285, 300, 315, 330, 345, 360, 375,
       390, 405, 420, 435, 450, 465, 480, 495, 510, 525, 540, 555, 570,
       585, 600, 615, 630, 645, 660, 675, 690, 705, 720, 735, 750, 765,
       780, 795, 810, 825, 840, 855, 870, 885, 900, 915, 930, 945, 960,
       975, 990])

In [6]:
fives_n_threes.shape

(67,)

In [7]:
fives_n_threes.ndim

1

In [8]:
np.array([[i for i in range(50)], [i*i for i in range(50)]], dtype = np.int64)

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
          11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
          22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
          33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
          44,   45,   46,   47,   48,   49],
       [   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
         121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
         484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
        1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
        1936, 2025, 2116, 2209, 2304, 2401]], dtype=int64)

In [9]:
np.zeros([5, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones([2, 10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
np.random.randint(low = -100, high = 100, size = [3, 15])

array([[ 10,  19,  56, -26,  40, -87, -66,  -5,  47, -64, -99, -46,  88,
        -70,  96],
       [ 66,   5, -12, -32, -74,  68, -47,  57, -51, -42,  -5,  73, -86,
         64, -18],
       [ 57, -18, -31,  17, -36, -69,  61,  12,  -6,   3,  91, -65, -66,
        -92,  68]])

In [16]:
# loc = mean, scale = sd
dnorm = np.random.normal(loc = 10.5, scale = 0.5, size = 20)

In [17]:
dnorm

array([ 9.9928969 , 10.18035771,  9.84544334,  9.87346419, 10.42986219,
       10.44558441, 10.1028432 , 10.36405957, 11.43699806, 10.52883135,
       10.0796542 , 11.52719833, 10.8974808 , 11.48006452, 10.45964098,
       11.20749715, 11.33475215, 10.69820058, 10.5104346 , 10.86771295])

In [18]:
dnorm.dtype.name

'float64'

In [19]:
# vectorized operations
nums = np.arange(0, 100, 2.5)

In [22]:
nums * 1.25

array([  0.   ,   3.125,   6.25 ,   9.375,  12.5  ,  15.625,  18.75 ,
        21.875,  25.   ,  28.125,  31.25 ,  34.375,  37.5  ,  40.625,
        43.75 ,  46.875,  50.   ,  53.125,  56.25 ,  59.375,  62.5  ,
        65.625,  68.75 ,  71.875,  75.   ,  78.125,  81.25 ,  84.375,
        87.5  ,  90.625,  93.75 ,  96.875, 100.   , 103.125, 106.25 ,
       109.375, 112.5  , 115.625, 118.75 , 121.875])

In [24]:
nums / 12.5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8])

In [25]:
nums - 12.5

array([-12.5, -10. ,  -7.5,  -5. ,  -2.5,   0. ,   2.5,   5. ,   7.5,
        10. ,  12.5,  15. ,  17.5,  20. ,  22.5,  25. ,  27.5,  30. ,
        32.5,  35. ,  37.5,  40. ,  42.5,  45. ,  47.5,  50. ,  52.5,
        55. ,  57.5,  60. ,  62.5,  65. ,  67.5,  70. ,  72.5,  75. ,
        77.5,  80. ,  82.5,  85. ])

In [26]:
# matrices
np.zeros([3, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
mat_zeroes = np.zeros([2, 10])
mat_zeroes

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
mat_zeroes + 20.5

array([[20.5, 20.5, 20.5, 20.5, 20.5, 20.5, 20.5, 20.5, 20.5, 20.5],
       [20.5, 20.5, 20.5, 20.5, 20.5, 20.5, 20.5, 20.5, 20.5, 20.5]])

In [29]:
mat_zeroes[1][8] = 78.1256

In [30]:
mat_zeroes

array([[ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    , 78.1256,  0.    ]])

In [33]:
# numbers linearly spaced within a range (limits)
np.linspace(100, 1000, num = 20)

array([ 100.        ,  147.36842105,  194.73684211,  242.10526316,
        289.47368421,  336.84210526,  384.21052632,  431.57894737,
        478.94736842,  526.31578947,  573.68421053,  621.05263158,
        668.42105263,  715.78947368,  763.15789474,  810.52631579,
        857.89473684,  905.26315789,  952.63157895, 1000.        ])